blog/urls.py
from django.conf.urls import url
from . import views
from .feeds import LatestPostsFeed

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    # url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
    url(r'^feed/$', LatestPostsFeed(), name='post_feed'),
    url(r'^search/$', views.post_search, name='post_search'),


]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):

    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')



class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.strftime('%m'),
                                                 self.publish.strftime('%d'),
                                                 self.slug])

    def __str__(self):
        return self.title



class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    # email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.core.mail import send_mail
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm
from taggit.models import Tag
from django.db.models import Count
from haystack.query import SearchQuerySet



class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    # posts = Post.published.all()
    #
    # # Paginator
    # object_list = Post.objects.all()
    # paginator = Paginator(object_list, 3)
    # page = request.GET.get('page')
    # tag = None
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page,
                                                   'posts': posts,
                                                   'tag': tag})



def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    # context = {'post': post}
    comments = post.comments.filter(active=True)

    if request.method == 'POST':
        #A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assing the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
            comment_form = CommentForm()
    else:
        comment_form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    return render(request,'blog/post/detail.html', {'post': post,
                                                    'comments': comments,
                                                    'comment_form': comment_form,
                                                    'similar_posts': similar_posts})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # if the forms is valid, we retrieve the validated data accessing
            # form.cleaned_data.This attribute is a dictionary of form fields
            # and their values.
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} recomendou você ler "{}"'.format(cd['name'], post.title)
            message = 'Leia "{}" no seguinte link: \n{}\n\n{} comentou: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'marshalmori@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})



def post_search(request):
    form = SearchForm()
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            cd = form.cleaned_data
            results = SearchQuerySet().models(Post).filter(content=cd['query']).load_all()
            # count total results
            total_results = results.count()

        return render(request, 'blog/post/search.html', {'form': form,
                                                     'cd': cd,
                                                     'results': results,
                                                     'total_results': total_results})
    return render(request, 'blog/post/search.html', {'form': form})

blog/templates/blog/base.html
{% load blog_tags %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Starter Template - Materialize</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static "css/materialize.css" %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static "css/style.css" %}" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body>
  <nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="{% url 'blog:post_list' %}" class="brand-logo">Marshal</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="#">Navbar Link</a></li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="#">Navbar Link</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>
  <div class="section no-pad-bot" id="index-banner">
    <div class="container">
      <br><br>
      {% block content %}
      {% endblock content %}

      <!-- <h1 class="header center orange-text">Starter Template</h1>
      <div class="row center">
        <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
      </div>
      <div class="row center">
        <a href="http://materializecss.com/getting-started.html" id="download-button" class="btn-large waves-effect waves-light orange">Get Started</a>
      </div>
      <br><br> -->

    </div>
  </div>


  <div class="container">
    <div class="section">

      <p class="purple-text darken-4-text">Meu blog tem um total de {% total_posts %} posts publicados.</p>

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">event_note</i></h2>
            <h5 class="center">Quantidade de Posts</h5>

            <p class="light">Até o presente momento temos <strong><span class="purple-text darken-4-text" >{% total_posts %}</span></strong> posts em nossa plataforma e esse valor não para de crescer.
              Nossa quantidade cresce devido ao grande interesse do escritor em divulgar suas pesquisas com o público em geral.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">group</i></h2>
            <h5 class="center">Últimos Posts Publicados</h5>
            <p class="light">{% show_latest_posts 5%}</p>
          </div>
        </div>

        <div class=" center col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">settings</i></h2>
            <h5 class="center">Posts mais Comentados</h5>
              {% get_most_commented_posts as most_commented_posts %}
              <ul>
                {% for post in most_commented_posts %}
                  <li>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                  </li>
                {% endfor %}
              </ul>
          </div>
        </div>
      </div>

    </div>
    <br><br>
  </div>

  <footer class="page-footer orange">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">RSS</h5>
          <p class="grey-text text-lighten-4"><a href="{% url 'blog:post_feed' %}">Inscrever no RSS</a></p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Settings</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="orange-text text-lighten-3" href="https://www.linkedin.com/in/marshal-mori-cavalheiro-715ab08/">Marshal</a>
      </div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="/static/js/materialize.js"></script>
  <script src="/static/js/init.js"></script>

  </body>
</html>

blog/templates/blog/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Anterior <<</a>
    {% endif %}
    <span class="current">
      Página {{ page.number }} de {{ page.paginator.num_pages }}
    </span>
      {% if page.has_next %}
          <a href="?page={{ page.next_page_number }}"> >> Próxima</a>
      {% endif %}
  </span>
</div>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %} {{ post.title }} {% endblock title %}


  {% block content %}
    <h4>{{ post.title }}</h4>
    <hr>
    <p>
      <strong>Publicado: {{ post.publish }}</strong> <br>
      <strong>Autor: {{ post.author }}</strong>
    </p>
    <hr>

    {{ post.body|markdown }}

    <br><br>

    <p>
      <a href="{% url 'blog:post_share' post.id %}" class="waves-effect waves-light btn"><i class="material-icons left">screen_share</i>Compartilhar</a>
    </p>
    <hr>
      <h4>Posts similares</h4>
      {% for post in similar_posts %}
          <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
          </p>
      {% empty %}
          Não há posts similares.
      {% endfor %}

    <hr>

    {% with comments.count as total_comments %}
      <h6>
          Quantidade de comentário{{ total_comments|pluralize }} : {{ total_comments }}
      </h6>
    {% endwith %}
    <hr>

    {% for comment in comments  %}
      <div>
        <p>
          <strong>
          Comentário {{ forloop.counter }} : {{ comment.name }} <br>
          Data/Hora : {{ comment.created }}
          </strong>
        </p>
        {{ comment.body|markdown }}
        <hr>
      </div>
    {% empty %}
      <p>Não há comentários ainda.</p>
    {% endfor %}

    {% if new_comment %}
      <h4>Seu comentário foi adicionado com sucesso!!</h4>
    {% else %}
      <h5>Adicione um novo comentário</h5>
      <div class="row">
        <form class='col s6'  method="post">
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button class="btn waves-effect waves-light" type="submit">Enviar
              <i class="material-icons right">send</i>
          </button>
        </form>
      </div>
    {% endif %}



  {% endblock content %}

blog/templates/blog/post/latest_posts.html
<div class="center">
  <ul>
    {% for post in latest_posts  %}
        <li>
          <a href="{{ post.get_absolute_url}}">{{ post.title}}</a>
        </li>
    {% endfor %}
  </ul>

</div>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Blog do Marshal{% endblock title %}


{% block content %}

  {% if tag %}
      <h6>Posts com a tag "{{ tag.name }}"</h6>
  {% endif %}
  {% for post in posts %}


    <h5>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </h5>

    <p class="date">Publicado em: {{ post.publish }} por {{ post.author }}</p>
    <!-- <p>Tags: {{ post.tags.all|join:", " }}</p> -->
    Tags:
    {% for tag in post.tags.all %}
        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
          {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
    {% endfor %}

    {{ post.body|markdown|truncatewords_html:60 }}
    <hr>
  {% endfor %}

  {% include "blog/pagination.html" with page=posts %}
  <hr>
{% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}

{% block title %}Pesquisa{% endblock %}

{% block content %}
  {% if "query" in request.GET %}
    <h1>Posts contendo "{{ cd.query }}"</h1>
    <h3>Encontrado {{ total_results }} resultado{{ total_results|pluralize }}</h3>
    {% for result in results %}
      {% with post=result.object %}
          <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
          {{ post.body|truncatewords:10 }}
      {% endwith %}
    {% empty %}
      <p>Não há resultados para essa busca.</p>
    {% endfor %}
      <p><a href="{% url 'blog:post_search' %}">Pesquisar novamente</a></p>
    {% else %}
      <h1>Pesquisar por posts</h1>
      <form action="." method="get">
        {{ form.as_p }}
        <button class="btn waves-effect waves-light" type="submit">Pesquisar
            <i class="material-icons right">send</i>
        </button>
      </form>
    {% endif %}
    {% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Compartilhando Post{% endblock %}

{% block content %}
  {% if sent %}
      <h5>E-mail enviado com sucesso</h5>
      <p>
        "{{ post.title }}" foi enviado com sucesso para o endereço: {{ form.to }}
      </p>
  {% else %}
    <h5>Compartilhe por email - "{{ post.title }}" - por email.</h5>
    <div class="row">
      <form class='col s6' action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <button class="btn waves-effect waves-light" type="submit">Enviar
            <i class="material-icons right">send</i>
        </button>
        
      </form>
    </div>
  {% endif %}
{% endblock %}